version: '3'

vars:
  PROJECT_ROOT: '{{.TASK_DIR}}'

  BIN_DIR: '{{.HOME}}/.local/bin'
  CONFIG_HOME: '{{if .XDG_CONFIG_HOME}}{{.XDG_CONFIG_HOME}}{{else}}{{.HOME}}/.config{{end}}'
  MANY_CONFIG: '{{.CONFIG_HOME}}/many'
  DATA_HOME: '{{if .XDG_DATA_HOME}}{{.XDG_DATA_HOME}}{{else}}{{.HOME}}/.local/share{{end}}'
  OPT_DIR: '{{.HOME}}/.local/opt'

  CLIPCASCADE_PORT: 15186

tasks:
  clipcascade:
    desc: Install ClipCascade server and client
    deps: [clipcascade:server, clipcascade:client, clipcascade:service]

  clipcascade:server:
    desc: Install ClipCascade server
    preconditions:
      - sh: '[ ! -d {{.OPT_DIR}}/ClipCascade-Server ]'
        msg: "ClipCascade-Server already exists in \"{{.OPT_DIR}}\"."
    cmds:
      - mkdir -p {{.OPT_DIR}}/ClipCascade-Server
      - |
        wget --no-clobber 'https://github.com/Sathvik-Rao/ClipCascade/releases/download/3.0.0/ClipCascade-Server-JRE_17.jar' \
        -P {{.OPT_DIR}}/ClipCascade-Server

  clipcascade:client:
    desc: Install ClipCascade client
    preconditions:
      - sh: '[ ! -d {{.OPT_DIR}}/ClipCascade ]'
        msg: "ClipCascade already exists in \"{{.OPT_DIR}}\"."
    cmds:
      - wget --no-clobber 'https://github.com/Sathvik-Rao/ClipCascade/releases/download/3.0.0/ClipCascade_Linux.tar.xz'
      - mkdir -p {{.OPT_DIR}}
      - tar -xf "ClipCascade_Linux.tar.xz" -C {{.OPT_DIR}}
      - cd {{.OPT_DIR}}/ClipCascade && python3 -m venv .venv
      - cd {{.OPT_DIR}}/ClipCascade && .venv/bin/pip install -r requirements.txt
      - cp {{.PROJECT_ROOT}}/clipcascade/DATA {{.OPT_DIR}}/ClipCascade/

  clipcascade:service:
    desc: Install ClipCascade systemd service
    cmds:
      - mkdir -p {{.CONFIG_HOME}}/systemd/user
      - ln -sf {{.PROJECT_ROOT}}/clipcascade/clipcascade.service {{.CONFIG_HOME}}/systemd/user/
      - systemctl --user daemon-reload

  lninstall:
    desc: Install Many files
    cmds:
      - mkdir -p {{.CONFIG_HOME}}
      - ln -sf {{.PROJECT_ROOT}}/config {{.CONFIG_HOME}}/
      
      - mkdir -p {{.MANY_CONFIG}}/xdgconfig
      - ln -sf {{.CONFIG_HOME}}/kcminputrc {{.MANY_CONFIG}}/xdgconfig
      
      - mkdir -p {{.MANY_CONFIG}}/xdgconfig/many
      - ln -sf {{.MANY_CONFIG}}/launcher_apps {{.MANY_CONFIG}}/xdgconfig/many/
      
      - mkdir -p {{.BIN_DIR}}
      - ln -sf {{.PROJECT_ROOT}}/bin/* {{.BIN_DIR}}/
      
      - mkdir -p {{.DATA_HOME}}/applications
      - ln -sf {{.PROJECT_ROOT}}/share/applications/* {{.DATA_HOME}}/applications/
